apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-eks-test-backend.fullname" . }}
  labels:
    {{- include "aws-eks-test-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aws-eks-test-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aws-eks-test-backend.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "aws-eks-test-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              {{ default 8080 .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ default 8080 .Values.service.internalPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: "PORT"
              value: {{ .Values.service.internalPort }}
              
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
