apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-eks-test-backend.fullname" . }}
  labels:
    {{- include "aws-eks-test-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "aws-eks-test-backend.selectorLabels" . | nindent 4 }}
